<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Macros -->
    <xacro:property name="chassi_radius" value="0.093" />
    <xacro:property name="chassi_length" value="0.045" />

    <xacro:property name="body_radius" value="0.11" />
    <xacro:property name="body_length" value="0.345" />

    <xacro:property name="wheel_radius" value="0.035" />
    <xacro:property name="wheel_length" value="0.028" />


    <!-- Links -->

    <link name="base_footprint" />

    <link name="base_link" />

    <link name="chassi">
        <visual>
            <origin xyz="0.0 0.0 ${chassi_length/2}" rpy="0.0 0.0 0.0" />
            <geometry>
                <cylinder radius="${chassi_radius}" length="${chassi_length}" />
            </geometry>
            <material name="black" />
        </visual>

    </link>

    <link name="body">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <geometry>
                <cylinder radius="${body_radius}" length="${body_length}" />
            </geometry>
            <material name="yellow" />
        </visual>

    </link>

    <xacro:macro name="wheel_link" params="prefix ">
        <link name="${prefix}_wheel">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <material name="blue" />
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="0.3" r="${wheel_radius}" h="${wheel_length}"
                xyz="0 0 0" rpy="${pi/2} 0.0 0.0" />
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />

    <xacro:macro name="caster_wheel_link" params="prefix">
        <link name="caster_wheel_${prefix}">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <sphere radius="${wheel_radius/2}" />
                </geometry>
            </visual>

        </link>
    </xacro:macro>

    <xacro:caster_wheel_link prefix="front" />
    <xacro:caster_wheel_link prefix="rear" />

</robot>